# Numpy Python

In [5]:
import numpy as np

### Creating array from list

In [6]:
arr_1d=np.array([1,2,3,4,5,6])
print("1d Array",arr_1d)

1d Array [1 2 3 4 5 6]


In [7]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print("2d Array",arr_2d)

2d Array [[1 2 3]
 [4 5 6]]


### List vs Numpy

In [10]:
pylist=[1,2,3]
print("list Multplication",pylist*2)

list Multplication [1, 2, 3, 1, 2, 3]


In [11]:
nparray=np.array([1,2,3])
print("python array Multiplication",nparray * 2)

python array Multiplication [2 4 6]


### Execution time differnce b/w python list and numpy array

In [17]:
import time
start=time.time()
pylist=[i*2 for i in range(10000000)]
print("Python List Execution Time:", time.time()-start)
import time
start=time.time()
numpyarray=np.arange(10000000) * 2 
print("Numpy Array Execution Time:", time.time()-start)

Python List Execution Time: 1.2110381126403809
Numpy Array Execution Time: 0.08573675155639648


### Creating array from scratch

In [23]:
zeros = np.zeros((3,4))
print("Zeros Array\n",zeros)
ones = np.ones((3,4))
print("Ones Array\n",ones)
full=np.full((3,3),6)
print("Full Array\n",full)
random=np.random.random((3,3))
print("Random Array\n",random)
sequence= np.arange(0,10,2)
print("Sequence Array",sequence)

Zeros Array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
Random Array
 [[0.23777003 0.93996943 0.26100295]
 [0.58998693 0.47755108 0.02926475]
 [0.52409401 0.31671841 0.60367237]]
Sequence Array [0 2 4 6 8]
