# Numpy Array Operations

In [4]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
print("Basic Slicing",arr[2:4])

Basic Slicing [3 4]


In [6]:
arr_2d=np.array([[1,2,3],
                 [4,5,6]])
print("Specfic Element",arr_2d[1,2])
print("Entire Row:",arr_2d[1])
print("Entire Column:",arr_2d[:,1])

Specfic Element 6
Entire Row: [4 5 6]
Entire Column: [2 5]


## Sorting

In [7]:
unsorted=np.array([1,3,4,1,2,7,4,3])
print("Sorted Array:",np.sort(unsorted))
arr_2d_unsorted=np.array([[1,2],
                         [3,4],
                         [1,2]])
print("Sorted array by Column:\n",np.sort(arr_2d_unsorted,axis=0))

Sorted Array: [1 1 2 3 3 4 4 7]
Sorted array by Column:
 [[1 2]
 [1 2]
 [3 4]]


## Filtering

In [8]:
numbers=np.array([1,3,4,5,1,6,4,5,3])
even_numbers=numbers[numbers%2==0]
print("Even Numbers:",even_numbers)

Even Numbers: [4 6 4]


## Filter with Mask


In [9]:
mask=numbers>=5
print("Numbers with filter and mask",numbers[mask])

Numbers with filter and mask [5 6 5]


## Fancy indexing vs np.where()

In [10]:
indices=[1,2,3]
print(numbers[indices])
where= np.where(numbers>4)
print("Numbers with np.where",numbers[where])
# conditional clause as if/elsenumbers>5,numbers*2,numbers
conditonarray=np.where(numbers>5,numbers*2,numbers)
print(conditonarray)

[3 4 5]
Numbers with np.where [5 6 5]
[ 1  3  4  5  1 12  4  5  3]
