# Numpy Array Operations

In [4]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
print("Basic Slicing",arr[2:4])

Basic Slicing [3 4]


In [6]:
arr_2d=np.array([[1,2,3],
                 [4,5,6]])
print("Specfic Element",arr_2d[1,2])
print("Entire Row:",arr_2d[1])
print("Entire Column:",arr_2d[:,1])

Specfic Element 6
Entire Row: [4 5 6]
Entire Column: [2 5]


## Sorting

In [7]:
unsorted=np.array([1,3,4,1,2,7,4,3])
print("Sorted Array:",np.sort(unsorted))
arr_2d_unsorted=np.array([[1,2],
                         [3,4],
                         [1,2]])
print("Sorted array by Column:\n",np.sort(arr_2d_unsorted,axis=0))

Sorted Array: [1 1 2 3 3 4 4 7]
Sorted array by Column:
 [[1 2]
 [1 2]
 [3 4]]


## Filtering

In [8]:
numbers=np.array([1,3,4,5,1,6,4,5,3])
even_numbers=numbers[numbers%2==0]
print("Even Numbers:",even_numbers)

Even Numbers: [4 6 4]


## Filter with Mask


In [9]:
mask=numbers>=5
print("Numbers with filter and mask",numbers[mask])

Numbers with filter and mask [5 6 5]


## Fancy indexing vs np.where()

In [10]:
indices=[1,2,3]
print(numbers[indices])
where= np.where(numbers>4)
print("Numbers with np.where",numbers[where])
# conditional clause as if/elsenumbers>5,numbers*2,numbers
conditonarray=np.where(numbers>5,numbers*2,numbers)
print(conditonarray)

[3 4 5]
Numbers with np.where [5 6 5]
[ 1  3  4  5  1 12  4  5  3]


## Adding & Removing Data

In [12]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatiability

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
d=np.array([10,11,12])
print("Compatiable shapes",a.shape==b.shape)

Compatiable shapes True


In [21]:
array=np.array([[1,2,3],[4,5,6]])
new_row=np.array([7,8,9])
with_row=np.vstack((array,new_row))
print("Adding new row:\n",with_row)
newcol=np.array([[10],[11]])
with_col=np.hstack((array,newcol))
print("Adding new column:\n",with_col)

# Array Deletion
arr=np.array([1,2,3,4,5])
print("Original Array:",arr)
arr=np.delete(arr,1)
print("After Deletion:",arr)

Adding new row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Adding new column:
 [[ 1  2  3 10]
 [ 4  5  6 11]]
Original Array: [1 2 3 4 5]
After Deletion: [1 3 4 5]
