In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [15]:
sales_data=np.array([
    [1, 150000, 200000, 250000,300000],
    [2, 200000, 250000, 300000,350000],
    [3, 250000, 300000, 350000,400000],
    [4, 300000, 350000, 400000,450000],
    [5, 350000, 400000, 450000,500000],
    [6, 400000, 450000, 500000,550000],
    [7, 450000, 500000, 550000,600000],
    [8, 500000, 550000, 600000,650000]
])
print("Zomato Sales Analysis")
print("\n Sales Data Shape:",sales_data.shape)
print("\n Sales Data for 1st 3 Restaurants\n",sales_data[0:3])
print("Sales Data:\n",sales_data[:,1:])
print("Total Sales Per Year:\n",np.sum(sales_data[:,1:], axis=0))
min_sales=np.min(sales_data[:,1:], axis=1)
print("Minimum Sales Per Restaurant:\n",min_sales)

Zomato Sales Analysis

 Sales Data Shape: (8, 5)

 Sales Data for 1st 3 Restaurants
 [[     1 150000 200000 250000 300000]
 [     2 200000 250000 300000 350000]
 [     3 250000 300000 350000 400000]]
Sales Data:
 [[150000 200000 250000 300000]
 [200000 250000 300000 350000]
 [250000 300000 350000 400000]
 [300000 350000 400000 450000]
 [350000 400000 450000 500000]
 [400000 450000 500000 550000]
 [450000 500000 550000 600000]
 [500000 550000 600000 650000]]
Total Sales Per Year:
 [2600000 3000000 3400000 3800000]
Minimum Sales Per Restaurant:
 [150000 200000 250000 300000 350000 400000 450000 500000]
